// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void ZoomCircleIn_Animation(lv_obj_t * TargetObject, int delay);
void ZoomCircleOut_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Idle
void ui_Idle_screen_init(void);
lv_obj_t * ui_Idle;
lv_obj_t * ui_BottomRowS1;
lv_obj_t * ui_LeftColS1;
lv_obj_t * ui_InOutIconS4;
lv_obj_t * ui_InOutTextS4;
lv_obj_t * ui_CenterColS1;
lv_obj_t * ui_ScanIconS1;
lv_obj_t * ui_ScanTextS1;
lv_obj_t * ui_RightColS1;
lv_obj_t * ui_InOutIconS1;
lv_obj_t * ui_InOutTextS1;
lv_obj_t * ui_MinusIconS1;
lv_obj_t * ui_TopRowS1;
lv_obj_t * ui_Circle1S1;
lv_obj_t * ui_Circle1TextS1;
lv_obj_t * ui_Divider1S1;
lv_obj_t * ui_Circle2S1;
lv_obj_t * ui_Circle2TextS1;
lv_obj_t * ui_Divider2S1;
lv_obj_t * ui_Circle3S1;
lv_obj_t * ui_Circle3TextS1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Image6;
lv_obj_t * ui_BatteryS1;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Image11;


// SCREEN: ui_Scanning
void ui_Scanning_screen_init(void);
lv_obj_t * ui_Scanning;
lv_obj_t * ui_TopRowS3;
lv_obj_t * ui_Circle1S3;
lv_obj_t * ui_Circle1TextS3;
lv_obj_t * ui_Divider1S3;
lv_obj_t * ui_Circle2S3;
lv_obj_t * ui_Circle2TextS3;
lv_obj_t * ui_Divider2S3;
lv_obj_t * ui_Circle3S3;
lv_obj_t * ui_Circle3TextS3;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Spinner3;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Container8;
lv_obj_t * ui_Image7;
lv_obj_t * ui_BatteryS2;


// SCREEN: ui_Result
void ui_Result_screen_init(void);
lv_obj_t * ui_Result;
lv_obj_t * ui_TopRowS4;
lv_obj_t * ui_Circle1S4;
lv_obj_t * ui_Circle1TextS4;
lv_obj_t * ui_Divider1S4;
lv_obj_t * ui_Circle2S4;
lv_obj_t * ui_Circle2TextS4;
lv_obj_t * ui_Divider2S4;
lv_obj_t * ui_Circle3S4;
lv_obj_t * ui_Circle3TextS4;
lv_obj_t * ui_Label3;
lv_obj_t * ui_BottomRowS3;
lv_obj_t * ui_LeftColS3;
lv_obj_t * ui_CenterColS3;
lv_obj_t * ui_ScanIconS3;
lv_obj_t * ui_ScanTextS3;
lv_obj_t * ui_RightColS3;
lv_obj_t * ui_InOutIconS3;
lv_obj_t * ui_InOutTextS3;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Image1;
lv_obj_t * ui_ResultSize;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Image3;
lv_obj_t * ui_ResultCol;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Image4;
lv_obj_t * ui_ResultShape;
lv_obj_t * ui_Container9;
lv_obj_t * ui_Image8;
lv_obj_t * ui_BatteryS3;


// SCREEN: ui_Startup
void ui_Startup_screen_init(void);
lv_obj_t * ui_Startup;
lv_obj_t * ui_Container7;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Image12;


// SCREEN: ui_ResultColor
void ui_ResultColor_screen_init(void);
lv_obj_t * ui_ResultColor;
lv_obj_t * ui_TopRowS2;
lv_obj_t * ui_Circle1S2;
lv_obj_t * ui_Circle1TextS2;
lv_obj_t * ui_Divider1S2;
lv_obj_t * ui_Circle2S2;
lv_obj_t * ui_Circle2TextS2;
lv_obj_t * ui_Divider2S2;
lv_obj_t * ui_Circle3S2;
lv_obj_t * ui_Circle3TextS2;
lv_obj_t * ui_Label7;
lv_obj_t * ui_BottomRowS2;
lv_obj_t * ui_LeftColS2;
lv_obj_t * ui_CenterColS2;
lv_obj_t * ui_ScanIconS2;
lv_obj_t * ui_ScanTextS2;
lv_obj_t * ui_RightColS2;
lv_obj_t * ui_InOutIconS2;
lv_obj_t * ui_InOutTextS2;
lv_obj_t * ui_Container10;
lv_obj_t * ui_ResultColorBackground;
lv_obj_t * ui_ResultColorText;
lv_obj_t * ui_Container14;
lv_obj_t * ui_Image16;
lv_obj_t * ui_BatteryS4;


// SCREEN: ui_Error
void ui_Error_screen_init(void);
lv_obj_t * ui_Error;
lv_obj_t * ui_BottomRowS5;
lv_obj_t * ui_LeftColS5;
lv_obj_t * ui_CenterColS5;
lv_obj_t * ui_ScanIconS5;
lv_obj_t * ui_ScanTextS5;
lv_obj_t * ui_RightColS5;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Container13;
lv_obj_t * ui_Image17;
lv_obj_t * ui_BatteryS7;


// SCREEN: ui_ResultNotFound
void ui_ResultNotFound_screen_init(void);
lv_obj_t * ui_ResultNotFound;
lv_obj_t * ui_TopRowS5;
lv_obj_t * ui_Circle1S5;
lv_obj_t * ui_Circle1TextS5;
lv_obj_t * ui_Divider1S5;
lv_obj_t * ui_Circle2S5;
lv_obj_t * ui_Circle2TextS5;
lv_obj_t * ui_Divider2S5;
lv_obj_t * ui_Circle3S5;
lv_obj_t * ui_Circle3TextS5;
lv_obj_t * ui_Label10;
lv_obj_t * ui_BottomRowS4;
lv_obj_t * ui_LeftColS4;
lv_obj_t * ui_CenterColS4;
lv_obj_t * ui_ScanIconS4;
lv_obj_t * ui_ScanTextS4;
lv_obj_t * ui_RightColS4;
lv_obj_t * ui_Container16;
lv_obj_t * ui_Image18;
lv_obj_t * ui_BatteryS5;
lv_obj_t * ui_Container11;
lv_obj_t * ui_Image14;
lv_obj_t * ui_Label11;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void ZoomCircleIn_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 250);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_0, 0, 100);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_zoom);
    lv_anim_start(&PropertyAnimation_0);

}
void ZoomCircleOut_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 250);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_0, 0, -80);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_zoom);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Idle_screen_init();
    ui_Scanning_screen_init();
    ui_Result_screen_init();
    ui_Startup_screen_init();
    ui_ResultColor_screen_init();
    ui_Error_screen_init();
    ui_ResultNotFound_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Idle);
}
