// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_LeftRow;
extern lv_obj_t * ui_CenterCol;
extern lv_obj_t * ui_ScanIcon;
extern lv_obj_t * ui_ScanText;
extern lv_obj_t * ui_RightCol;
extern lv_obj_t * ui_InOutIcon;
extern lv_obj_t * ui_InOutText;
extern lv_obj_t * ui_MinusIcon;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_camera_solid_png);    // assets/camera_solid.png
LV_IMG_DECLARE(ui_img_plus_solid_png);    // assets/plus_solid.png
LV_IMG_DECLARE(ui_img_minus_solid_png);    // assets/minus_solid.png
LV_IMG_DECLARE(ui_img_circle_solid_png);    // assets/circle_solid.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
