// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_ResultColor_screen_init(void)
{
    ui_ResultColor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ResultColor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopRowS2 = lv_obj_create(ui_ResultColor);
    lv_obj_remove_style_all(ui_TopRowS2);
    lv_obj_set_width(ui_TopRowS2, 320);
    lv_obj_set_height(ui_TopRowS2, 60);
    lv_obj_set_x(ui_TopRowS2, 0);
    lv_obj_set_y(ui_TopRowS2, -75);
    lv_obj_set_align(ui_TopRowS2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopRowS2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopRowS2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopRowS2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Circle1S2 = lv_img_create(ui_TopRowS2);
    lv_img_set_src(ui_Circle1S2, &ui_img_circle_solid_green_png);
    lv_obj_set_width(ui_Circle1S2, 48);
    lv_obj_set_height(ui_Circle1S2, 48);
    lv_obj_set_x(ui_Circle1S2, -124);
    lv_obj_set_y(ui_Circle1S2, -13);
    lv_obj_set_align(ui_Circle1S2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Circle1S2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Circle1S2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Circle1S2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Circle1S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Circle1S2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Circle1S2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Circle1S2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Circle1TextS2 = lv_label_create(ui_Circle1S2);
    lv_obj_set_width(ui_Circle1TextS2, lv_pct(100));
    lv_obj_set_height(ui_Circle1TextS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Circle1TextS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Circle1TextS2, "1");
    lv_obj_set_style_text_color(ui_Circle1TextS2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Circle1TextS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Circle1TextS2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider1S2 = lv_obj_create(ui_TopRowS2);
    lv_obj_set_width(ui_Divider1S2, 80);
    lv_obj_set_height(ui_Divider1S2, 7);
    lv_obj_set_x(ui_Divider1S2, -60);
    lv_obj_set_y(ui_Divider1S2, -92);
    lv_obj_set_align(ui_Divider1S2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divider1S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Circle2S2 = lv_img_create(ui_TopRowS2);
    lv_img_set_src(ui_Circle2S2, &ui_img_circle_solid_green_png);
    lv_obj_set_width(ui_Circle2S2, 48);
    lv_obj_set_height(ui_Circle2S2, 48);
    lv_obj_set_x(ui_Circle2S2, -124);
    lv_obj_set_y(ui_Circle2S2, -13);
    lv_obj_set_align(ui_Circle2S2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Circle2S2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Circle2S2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Circle2S2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Circle2S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Circle2S2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Circle2S2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Circle2S2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Circle2S2, lv_color_hex(0x240909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Circle2S2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Circle2TextS2 = lv_label_create(ui_Circle2S2);
    lv_obj_set_width(ui_Circle2TextS2, lv_pct(100));
    lv_obj_set_height(ui_Circle2TextS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Circle2TextS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Circle2TextS2, "2");
    lv_obj_set_style_text_color(ui_Circle2TextS2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Circle2TextS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Circle2TextS2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider2S2 = lv_obj_create(ui_TopRowS2);
    lv_obj_set_width(ui_Divider2S2, 80);
    lv_obj_set_height(ui_Divider2S2, 7);
    lv_obj_set_x(ui_Divider2S2, -60);
    lv_obj_set_y(ui_Divider2S2, -92);
    lv_obj_set_align(ui_Divider2S2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divider2S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Circle3S2 = lv_img_create(ui_TopRowS2);
    lv_img_set_src(ui_Circle3S2, &ui_img_circle_solid_large_png);
    lv_obj_set_width(ui_Circle3S2, 48);
    lv_obj_set_height(ui_Circle3S2, 48);
    lv_obj_set_x(ui_Circle3S2, -124);
    lv_obj_set_y(ui_Circle3S2, -13);
    lv_obj_set_align(ui_Circle3S2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Circle3S2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Circle3S2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Circle3S2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Circle3S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Circle3TextS2 = lv_label_create(ui_Circle3S2);
    lv_obj_set_width(ui_Circle3TextS2, lv_pct(100));
    lv_obj_set_height(ui_Circle3TextS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Circle3TextS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Circle3TextS2, "3");
    lv_obj_set_style_text_color(ui_Circle3TextS2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Circle3TextS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Circle3TextS2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultHeadlineColor = lv_label_create(ui_ResultColor);
    lv_obj_set_width(ui_ResultHeadlineColor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultHeadlineColor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResultHeadlineColor, 0);
    lv_obj_set_y(ui_ResultHeadlineColor, -43);
    lv_obj_set_align(ui_ResultHeadlineColor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultHeadlineColor, "Ergebnis");
    lv_obj_set_style_text_color(ui_ResultHeadlineColor, lv_color_hex(0xCDCECD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResultHeadlineColor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomRowS2 = lv_obj_create(ui_ResultColor);
    lv_obj_remove_style_all(ui_BottomRowS2);
    lv_obj_set_width(ui_BottomRowS2, 320);
    lv_obj_set_height(ui_BottomRowS2, 80);
    lv_obj_set_x(ui_BottomRowS2, 0);
    lv_obj_set_y(ui_BottomRowS2, 80);
    lv_obj_set_align(ui_BottomRowS2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BottomRowS2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BottomRowS2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_BottomRowS2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_BottomRowS2, &ui_img_bg_arc_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BottomRowS2, lv_color_hex(0xCECECE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomRowS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeftColS2 = lv_obj_create(ui_BottomRowS2);
    lv_obj_remove_style_all(ui_LeftColS2);
    lv_obj_set_width(ui_LeftColS2, lv_pct(31));
    lv_obj_set_height(ui_LeftColS2, lv_pct(100));
    lv_obj_set_x(ui_LeftColS2, -4);
    lv_obj_set_y(ui_LeftColS2, -15);
    lv_obj_set_align(ui_LeftColS2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LeftColS2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_LeftColS2, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_LeftColS2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CenterColS2 = lv_obj_create(ui_BottomRowS2);
    lv_obj_remove_style_all(ui_CenterColS2);
    lv_obj_set_width(ui_CenterColS2, lv_pct(31));
    lv_obj_set_height(ui_CenterColS2, lv_pct(100));
    lv_obj_set_x(ui_CenterColS2, -4);
    lv_obj_set_y(ui_CenterColS2, -15);
    lv_obj_set_align(ui_CenterColS2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CenterColS2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CenterColS2, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CenterColS2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScanIconS2 = lv_img_create(ui_CenterColS2);
    lv_img_set_src(ui_ScanIconS2, &ui_img_home_solid_png);
    lv_obj_set_width(ui_ScanIconS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScanIconS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScanIconS2, -5);
    lv_obj_set_y(ui_ScanIconS2, 8);
    lv_obj_set_align(ui_ScanIconS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScanIconS2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ScanIconS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScanTextS2 = lv_label_create(ui_CenterColS2);
    lv_obj_set_width(ui_ScanTextS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScanTextS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScanTextS2, -5);
    lv_obj_set_y(ui_ScanTextS2, 12);
    lv_obj_set_align(ui_ScanTextS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScanTextS2, "Zurueck");
    lv_obj_set_style_text_font(ui_ScanTextS2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RightColS2 = lv_obj_create(ui_BottomRowS2);
    lv_obj_remove_style_all(ui_RightColS2);
    lv_obj_set_width(ui_RightColS2, lv_pct(31));
    lv_obj_set_height(ui_RightColS2, lv_pct(100));
    lv_obj_set_x(ui_RightColS2, -4);
    lv_obj_set_y(ui_RightColS2, -15);
    lv_obj_set_align(ui_RightColS2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RightColS2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_RightColS2, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RightColS2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InOutIconS2 = lv_img_create(ui_RightColS2);
    lv_img_set_src(ui_InOutIconS2, &ui_img_trash_alt_solid_png);
    lv_obj_set_width(ui_InOutIconS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InOutIconS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InOutIconS2, -5);
    lv_obj_set_y(ui_InOutIconS2, 13);
    lv_obj_set_align(ui_InOutIconS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InOutIconS2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_InOutIconS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InOutTextS2 = lv_label_create(ui_RightColS2);
    lv_obj_set_width(ui_InOutTextS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InOutTextS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InOutTextS2, -5);
    lv_obj_set_y(ui_InOutTextS2, 12);
    lv_obj_set_align(ui_InOutTextS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InOutTextS2, "Loeschen");

    ui_Container10 = lv_obj_create(ui_ResultColor);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 320);
    lv_obj_set_height(ui_Container10, 70);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ResultColorBackground = lv_obj_create(ui_Container10);
    lv_obj_set_width(ui_ResultColorBackground, 200);
    lv_obj_set_height(ui_ResultColorBackground, 50);
    lv_obj_set_x(ui_ResultColorBackground, 74);
    lv_obj_set_y(ui_ResultColorBackground, 11);
    lv_obj_set_align(ui_ResultColorBackground, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ResultColorBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultColorBackground, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultColorBackground, lv_color_hex(0x14BEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultColorBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResultColorBackground, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultColorText = lv_label_create(ui_ResultColorBackground);
    lv_obj_set_width(ui_ResultColorText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultColorText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultColorText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultColorText, "#A5C674");

    ui_Container14 = lv_obj_create(ui_ResultColor);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 28);
    lv_obj_set_height(ui_Container14, 15);
    lv_obj_set_x(ui_Container14, 142);
    lv_obj_set_y(ui_Container14, -110);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_img_create(ui_Container14);
    lv_img_set_src(ui_Image16, &ui_img_wifi_solid_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image16, 114);
    lv_obj_set_y(ui_Image16, 1);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryS4 = lv_img_create(ui_Container14);
    lv_img_set_src(ui_BatteryS4, &ui_img_battery_empty_solid_png);
    lv_obj_set_width(ui_BatteryS4, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_BatteryS4, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_BatteryS4, 147);
    lv_obj_set_y(ui_BatteryS4, -2);
    lv_obj_set_align(ui_BatteryS4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BatteryS4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BatteryS4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
