// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Step2_screen_init(void)
{
    ui_Step2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Step2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopRowS3 = lv_obj_create(ui_Step2);
    lv_obj_remove_style_all(ui_TopRowS3);
    lv_obj_set_width(ui_TopRowS3, 320);
    lv_obj_set_height(ui_TopRowS3, 60);
    lv_obj_set_x(ui_TopRowS3, 0);
    lv_obj_set_y(ui_TopRowS3, -75);
    lv_obj_set_align(ui_TopRowS3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopRowS3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopRowS3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopRowS3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Circle1S3 = lv_img_create(ui_TopRowS3);
    lv_img_set_src(ui_Circle1S3, &ui_img_circle_solid_green_png);
    lv_obj_set_width(ui_Circle1S3, 48);
    lv_obj_set_height(ui_Circle1S3, 48);
    lv_obj_set_x(ui_Circle1S3, -124);
    lv_obj_set_y(ui_Circle1S3, -13);
    lv_obj_set_align(ui_Circle1S3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Circle1S3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Circle1S3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Circle1S3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Circle1S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Circle1S3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Circle1S3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Circle1S3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Circle1S3, lv_color_hex(0xE31313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Circle1S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Circle1TextS3 = lv_label_create(ui_Circle1S3);
    lv_obj_set_width(ui_Circle1TextS3, lv_pct(100));
    lv_obj_set_height(ui_Circle1TextS3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Circle1TextS3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Circle1TextS3, "✔");
    lv_obj_set_style_text_color(ui_Circle1TextS3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Circle1TextS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Circle1TextS3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Circle1TextS3, &ui_font_NotoCheckEmoji, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider1S3 = lv_obj_create(ui_TopRowS3);
    lv_obj_set_width(ui_Divider1S3, 50);
    lv_obj_set_height(ui_Divider1S3, 7);
    lv_obj_set_x(ui_Divider1S3, -60);
    lv_obj_set_y(ui_Divider1S3, -92);
    lv_obj_set_align(ui_Divider1S3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divider1S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Divider1S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Circle2S3 = lv_img_create(ui_TopRowS3);
    lv_img_set_src(ui_Circle2S3, &ui_img_circle_solid_large_png);
    lv_obj_set_width(ui_Circle2S3, 48);
    lv_obj_set_height(ui_Circle2S3, 48);
    lv_obj_set_x(ui_Circle2S3, -124);
    lv_obj_set_y(ui_Circle2S3, -13);
    lv_obj_set_align(ui_Circle2S3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Circle2S3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Circle2S3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Circle2S3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Circle2S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Circle2S3, lv_color_hex(0x240909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Circle2S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Circle2TextS3 = lv_label_create(ui_Circle2S3);
    lv_obj_set_width(ui_Circle2TextS3, lv_pct(100));
    lv_obj_set_height(ui_Circle2TextS3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Circle2TextS3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Circle2TextS3, "2");
    lv_obj_set_style_text_color(ui_Circle2TextS3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Circle2TextS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Circle2TextS3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider2S3 = lv_obj_create(ui_TopRowS3);
    lv_obj_set_width(ui_Divider2S3, 50);
    lv_obj_set_height(ui_Divider2S3, 7);
    lv_obj_set_x(ui_Divider2S3, -60);
    lv_obj_set_y(ui_Divider2S3, -92);
    lv_obj_set_align(ui_Divider2S3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divider2S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Divider2S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Circle3S3 = lv_img_create(ui_TopRowS3);
    lv_img_set_src(ui_Circle3S3, &ui_img_circle_solid_png);
    lv_obj_set_width(ui_Circle3S3, 48);
    lv_obj_set_height(ui_Circle3S3, 48);
    lv_obj_set_x(ui_Circle3S3, -124);
    lv_obj_set_y(ui_Circle3S3, -13);
    lv_obj_set_align(ui_Circle3S3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Circle3S3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Circle3S3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Circle3S3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Circle3S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Circle3S3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Circle3S3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Circle3S3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Circle3TextS3 = lv_label_create(ui_Circle3S3);
    lv_obj_set_width(ui_Circle3TextS3, lv_pct(100));
    lv_obj_set_height(ui_Circle3TextS3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Circle3TextS3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Circle3TextS3, "3");
    lv_obj_set_style_text_color(ui_Circle3TextS3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Circle3TextS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Circle3TextS3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Step2);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 320);
    lv_obj_set_height(ui_Container2, 156);
    lv_obj_set_x(ui_Container2, -1);
    lv_obj_set_y(ui_Container2, 39);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner3 = lv_spinner_create(ui_Container2, 1000, 90);
    lv_obj_set_width(ui_Spinner3, 80);
    lv_obj_set_height(ui_Spinner3, 80);
    lv_obj_set_x(ui_Spinner3, -4);
    lv_obj_set_y(ui_Spinner3, 22);
    lv_obj_set_align(ui_Spinner3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner3, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner3, lv_color_hex(0xA43031), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -4);
    lv_obj_set_y(ui_Label1, 83);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Label1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Label1, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_Label1, "Scan laueft...");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusBarS3 = lv_obj_create(ui_Step2);
    lv_obj_remove_style_all(ui_StatusBarS3);
    lv_obj_set_width(ui_StatusBarS3, 40);
    lv_obj_set_height(ui_StatusBarS3, 20);
    lv_obj_set_x(ui_StatusBarS3, 140);
    lv_obj_set_y(ui_StatusBarS3, -110);
    lv_obj_set_align(ui_StatusBarS3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_StatusBarS3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_StatusBarS3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBarS3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_StatusBarS3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatusBarS3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatusBarS3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatusBarS3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIndicatorS3 = lv_img_create(ui_StatusBarS3);
    lv_img_set_src(ui_WifiIndicatorS3, &ui_img_wifi_solid_png);
    lv_obj_set_width(ui_WifiIndicatorS3, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_WifiIndicatorS3, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_WifiIndicatorS3, 130);
    lv_obj_set_y(ui_WifiIndicatorS3, -110);
    lv_obj_set_align(ui_WifiIndicatorS3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIndicatorS3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiIndicatorS3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryIndicatorS3 = lv_img_create(ui_StatusBarS3);
    lv_img_set_src(ui_BatteryIndicatorS3, &ui_img_battery_full_solid_png);
    lv_obj_set_width(ui_BatteryIndicatorS3, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_BatteryIndicatorS3, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_BatteryIndicatorS3, 150);
    lv_obj_set_y(ui_BatteryIndicatorS3, -110);
    lv_obj_set_align(ui_BatteryIndicatorS3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BatteryIndicatorS3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BatteryIndicatorS3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
