// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 320);
    lv_obj_set_height(ui_Container2, 80);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 80);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Container2, lv_color_hex(0xCECECE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeftRow = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_LeftRow);
    lv_obj_set_width(ui_LeftRow, lv_pct(31));
    lv_obj_set_height(ui_LeftRow, lv_pct(100));
    lv_obj_set_x(ui_LeftRow, -4);
    lv_obj_set_y(ui_LeftRow, -15);
    lv_obj_set_align(ui_LeftRow, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LeftRow, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_LeftRow, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_LeftRow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CenterCol = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_CenterCol);
    lv_obj_set_width(ui_CenterCol, lv_pct(31));
    lv_obj_set_height(ui_CenterCol, lv_pct(100));
    lv_obj_set_x(ui_CenterCol, -4);
    lv_obj_set_y(ui_CenterCol, -15);
    lv_obj_set_align(ui_CenterCol, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CenterCol, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CenterCol, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CenterCol, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScanIcon = lv_img_create(ui_CenterCol);
    lv_img_set_src(ui_ScanIcon, &ui_img_camera_solid_png);
    lv_obj_set_width(ui_ScanIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScanIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScanIcon, -26);
    lv_obj_set_y(ui_ScanIcon, -36);
    lv_obj_set_align(ui_ScanIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScanIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ScanIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScanText = lv_label_create(ui_CenterCol);
    lv_obj_set_width(ui_ScanText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScanText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScanText, -5);
    lv_obj_set_y(ui_ScanText, 12);
    lv_obj_set_align(ui_ScanText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScanText, "Scan");

    ui_RightCol = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_RightCol);
    lv_obj_set_width(ui_RightCol, lv_pct(31));
    lv_obj_set_height(ui_RightCol, lv_pct(100));
    lv_obj_set_x(ui_RightCol, -4);
    lv_obj_set_y(ui_RightCol, -15);
    lv_obj_set_align(ui_RightCol, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RightCol, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_RightCol, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RightCol, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InOutIcon = lv_img_create(ui_RightCol);
    lv_img_set_src(ui_InOutIcon, &ui_img_plus_solid_png);
    lv_obj_set_width(ui_InOutIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InOutIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InOutIcon, -5);
    lv_obj_set_y(ui_InOutIcon, 13);
    lv_obj_set_align(ui_InOutIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InOutIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_InOutIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InOutText = lv_label_create(ui_RightCol);
    lv_obj_set_width(ui_InOutText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InOutText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InOutText, -5);
    lv_obj_set_y(ui_InOutText, 12);
    lv_obj_set_align(ui_InOutText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InOutText, "Hinzufuegen");

    ui_MinusIcon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_MinusIcon, &ui_img_minus_solid_png);
    lv_obj_set_width(ui_MinusIcon, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_MinusIcon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_MinusIcon, 196);
    lv_obj_set_y(ui_MinusIcon, 53);
    lv_obj_set_align(ui_MinusIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MinusIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MinusIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 320);
    lv_obj_set_height(ui_Container3, 60);
    lv_obj_set_x(ui_Container3, -1);
    lv_obj_set_y(ui_Container3, -50);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Container3);
    lv_img_set_src(ui_Image2, &ui_img_circle_solid_png);
    lv_obj_set_width(ui_Image2, 32);
    lv_obj_set_height(ui_Image2, 32);
    lv_obj_set_x(ui_Image2, -124);
    lv_obj_set_y(ui_Image2, -13);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Image2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Image2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Image2);
    lv_obj_set_width(ui_Label1, lv_pct(100));
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "1");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel1, 80);
    lv_obj_set_height(ui_Panel1, 7);
    lv_obj_set_x(ui_Panel1, -60);
    lv_obj_set_y(ui_Panel1, -92);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Container3);
    lv_img_set_src(ui_Image1, &ui_img_circle_solid_png);
    lv_obj_set_width(ui_Image1, 32);
    lv_obj_set_height(ui_Image1, 32);
    lv_obj_set_x(ui_Image1, -124);
    lv_obj_set_y(ui_Image1, -13);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Image1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Image1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image1, lv_color_hex(0x240909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Image1);
    lv_obj_set_width(ui_Label2, lv_pct(100));
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "2");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel2, 80);
    lv_obj_set_height(ui_Panel2, 7);
    lv_obj_set_x(ui_Panel2, -60);
    lv_obj_set_y(ui_Panel2, -92);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Container3);
    lv_img_set_src(ui_Image3, &ui_img_circle_solid_png);
    lv_obj_set_width(ui_Image3, 32);
    lv_obj_set_height(ui_Image3, 32);
    lv_obj_set_x(ui_Image3, -141);
    lv_obj_set_y(ui_Image3, 83);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Image3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Image3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Image3);
    lv_obj_set_width(ui_Label3, lv_pct(100));
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "3");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

}
