// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Scanning_screen_init(void)
{
    ui_Scanning = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Scanning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopRowS3 = lv_obj_create(ui_Scanning);
    lv_obj_remove_style_all(ui_TopRowS3);
    lv_obj_set_width(ui_TopRowS3, 320);
    lv_obj_set_height(ui_TopRowS3, 60);
    lv_obj_set_x(ui_TopRowS3, 0);
    lv_obj_set_y(ui_TopRowS3, -75);
    lv_obj_set_align(ui_TopRowS3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopRowS3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopRowS3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopRowS3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Circle1S3 = lv_img_create(ui_TopRowS3);
    lv_img_set_src(ui_Circle1S3, &ui_img_circle_solid_green_png);
    lv_obj_set_width(ui_Circle1S3, 48);
    lv_obj_set_height(ui_Circle1S3, 48);
    lv_obj_set_x(ui_Circle1S3, -124);
    lv_obj_set_y(ui_Circle1S3, -13);
    lv_obj_set_align(ui_Circle1S3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Circle1S3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Circle1S3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Circle1S3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Circle1S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Circle1S3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Circle1S3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Circle1S3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Circle1S3, lv_color_hex(0xE31313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Circle1S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Circle1TextS3 = lv_label_create(ui_Circle1S3);
    lv_obj_set_width(ui_Circle1TextS3, lv_pct(100));
    lv_obj_set_height(ui_Circle1TextS3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Circle1TextS3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Circle1TextS3, "✔");
    lv_obj_set_style_text_color(ui_Circle1TextS3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Circle1TextS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Circle1TextS3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Circle1TextS3, &ui_font_NotoCheckEmoji, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider1S3 = lv_obj_create(ui_TopRowS3);
    lv_obj_set_width(ui_Divider1S3, 80);
    lv_obj_set_height(ui_Divider1S3, 7);
    lv_obj_set_x(ui_Divider1S3, -60);
    lv_obj_set_y(ui_Divider1S3, -92);
    lv_obj_set_align(ui_Divider1S3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divider1S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Circle2S3 = lv_img_create(ui_TopRowS3);
    lv_img_set_src(ui_Circle2S3, &ui_img_circle_solid_large_png);
    lv_obj_set_width(ui_Circle2S3, 48);
    lv_obj_set_height(ui_Circle2S3, 48);
    lv_obj_set_x(ui_Circle2S3, -124);
    lv_obj_set_y(ui_Circle2S3, -13);
    lv_obj_set_align(ui_Circle2S3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Circle2S3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Circle2S3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Circle2S3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Circle2S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Circle2S3, lv_color_hex(0x240909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Circle2S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Circle2TextS3 = lv_label_create(ui_Circle2S3);
    lv_obj_set_width(ui_Circle2TextS3, lv_pct(100));
    lv_obj_set_height(ui_Circle2TextS3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Circle2TextS3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Circle2TextS3, "2");
    lv_obj_set_style_text_color(ui_Circle2TextS3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Circle2TextS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Circle2TextS3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider2S3 = lv_obj_create(ui_TopRowS3);
    lv_obj_set_width(ui_Divider2S3, 80);
    lv_obj_set_height(ui_Divider2S3, 7);
    lv_obj_set_x(ui_Divider2S3, -60);
    lv_obj_set_y(ui_Divider2S3, -92);
    lv_obj_set_align(ui_Divider2S3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divider2S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Circle3S3 = lv_img_create(ui_TopRowS3);
    lv_img_set_src(ui_Circle3S3, &ui_img_circle_solid_png);
    lv_obj_set_width(ui_Circle3S3, 48);
    lv_obj_set_height(ui_Circle3S3, 48);
    lv_obj_set_x(ui_Circle3S3, -124);
    lv_obj_set_y(ui_Circle3S3, -13);
    lv_obj_set_align(ui_Circle3S3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Circle3S3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Circle3S3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Circle3S3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Circle3S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Circle3S3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Circle3S3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Circle3S3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Circle3TextS3 = lv_label_create(ui_Circle3S3);
    lv_obj_set_width(ui_Circle3TextS3, lv_pct(100));
    lv_obj_set_height(ui_Circle3TextS3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Circle3TextS3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Circle3TextS3, "3");
    lv_obj_set_style_text_color(ui_Circle3TextS3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Circle3TextS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Circle3TextS3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Scanning);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 320);
    lv_obj_set_height(ui_Container2, 170);
    lv_obj_set_x(ui_Container2, -1);
    lv_obj_set_y(ui_Container2, 30);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner3 = lv_spinner_create(ui_Container2, 1000, 90);
    lv_obj_set_width(ui_Spinner3, 80);
    lv_obj_set_height(ui_Spinner3, 80);
    lv_obj_set_align(ui_Spinner3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner3, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner3, lv_color_hex(0xA43031), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -4);
    lv_obj_set_y(ui_Label1, 83);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Label1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Label1, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_Label1, "Scan laueft...");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Scanning);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 28);
    lv_obj_set_height(ui_Container8, 15);
    lv_obj_set_x(ui_Container8, 142);
    lv_obj_set_y(ui_Container8, -110);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_Container8);
    lv_img_set_src(ui_Image7, &ui_img_wifi_solid_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image7, 114);
    lv_obj_set_y(ui_Image7, 1);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryS2 = lv_img_create(ui_Container8);
    lv_img_set_src(ui_BatteryS2, &ui_img_battery_empty_solid_png);
    lv_obj_set_width(ui_BatteryS2, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_BatteryS2, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_BatteryS2, 147);
    lv_obj_set_y(ui_BatteryS2, -2);
    lv_obj_set_align(ui_BatteryS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BatteryS2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BatteryS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
