// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Step4_screen_init(void)
{
    ui_Step4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Step4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopRowS2 = lv_obj_create(ui_Step4);
    lv_obj_remove_style_all(ui_TopRowS2);
    lv_obj_set_width(ui_TopRowS2, 320);
    lv_obj_set_height(ui_TopRowS2, 60);
    lv_obj_set_x(ui_TopRowS2, 0);
    lv_obj_set_y(ui_TopRowS2, -75);
    lv_obj_set_align(ui_TopRowS2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopRowS2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopRowS2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopRowS2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Circle1S2 = lv_img_create(ui_TopRowS2);
    lv_img_set_src(ui_Circle1S2, &ui_img_circle_solid_green_png);
    lv_obj_set_width(ui_Circle1S2, 48);
    lv_obj_set_height(ui_Circle1S2, 48);
    lv_obj_set_x(ui_Circle1S2, -124);
    lv_obj_set_y(ui_Circle1S2, -13);
    lv_obj_set_align(ui_Circle1S2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Circle1S2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Circle1S2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Circle1S2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Circle1S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Circle1S2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Circle1S2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Circle1S2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Circle1S2, lv_color_hex(0xE31313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Circle1S2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Circle1TextS2 = lv_label_create(ui_Circle1S2);
    lv_obj_set_width(ui_Circle1TextS2, lv_pct(100));
    lv_obj_set_height(ui_Circle1TextS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Circle1TextS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Circle1TextS2, "✔");
    lv_obj_set_style_text_color(ui_Circle1TextS2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Circle1TextS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Circle1TextS2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Circle1TextS2, &ui_font_NotoCheckEmoji, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider1S2 = lv_obj_create(ui_TopRowS2);
    lv_obj_set_width(ui_Divider1S2, 80);
    lv_obj_set_height(ui_Divider1S2, 7);
    lv_obj_set_x(ui_Divider1S2, -60);
    lv_obj_set_y(ui_Divider1S2, -92);
    lv_obj_set_align(ui_Divider1S2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divider1S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Circle2S2 = lv_img_create(ui_TopRowS2);
    lv_img_set_src(ui_Circle2S2, &ui_img_circle_solid_large_png);
    lv_obj_set_width(ui_Circle2S2, 48);
    lv_obj_set_height(ui_Circle2S2, 48);
    lv_obj_set_x(ui_Circle2S2, -124);
    lv_obj_set_y(ui_Circle2S2, -13);
    lv_obj_set_align(ui_Circle2S2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Circle2S2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Circle2S2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Circle2S2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Circle2S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Circle2S2, lv_color_hex(0x240909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Circle2S2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Circle2TextS2 = lv_label_create(ui_Circle2S2);
    lv_obj_set_width(ui_Circle2TextS2, lv_pct(100));
    lv_obj_set_height(ui_Circle2TextS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Circle2TextS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Circle2TextS2, "2");
    lv_obj_set_style_text_color(ui_Circle2TextS2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Circle2TextS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Circle2TextS2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider2S2 = lv_obj_create(ui_TopRowS2);
    lv_obj_set_width(ui_Divider2S2, 80);
    lv_obj_set_height(ui_Divider2S2, 7);
    lv_obj_set_x(ui_Divider2S2, -60);
    lv_obj_set_y(ui_Divider2S2, -92);
    lv_obj_set_align(ui_Divider2S2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divider2S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Circle3S2 = lv_img_create(ui_TopRowS2);
    lv_img_set_src(ui_Circle3S2, &ui_img_circle_solid_png);
    lv_obj_set_width(ui_Circle3S2, 48);
    lv_obj_set_height(ui_Circle3S2, 48);
    lv_obj_set_x(ui_Circle3S2, -124);
    lv_obj_set_y(ui_Circle3S2, -13);
    lv_obj_set_align(ui_Circle3S2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Circle3S2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Circle3S2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Circle3S2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Circle3S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Circle3S2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Circle3S2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Circle3S2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Circle3TextS2 = lv_label_create(ui_Circle3S2);
    lv_obj_set_width(ui_Circle3TextS2, lv_pct(100));
    lv_obj_set_height(ui_Circle3TextS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Circle3TextS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Circle3TextS2, "3");
    lv_obj_set_style_text_color(ui_Circle3TextS2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Circle3TextS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Circle3TextS2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_Step4);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 320);
    lv_obj_set_height(ui_Container6, 156);
    lv_obj_set_x(ui_Container6, -1);
    lv_obj_set_y(ui_Container6, 39);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner2 = lv_spinner_create(ui_Container6, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 80);
    lv_obj_set_height(ui_Spinner2, 80);
    lv_obj_set_x(ui_Spinner2, -4);
    lv_obj_set_y(ui_Spinner2, 22);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0xA43031), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -4);
    lv_obj_set_y(ui_Label5, 83);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Label5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Label5, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_Label5, "Analyse laueft...");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusBarS2 = lv_obj_create(ui_Step4);
    lv_obj_remove_style_all(ui_StatusBarS2);
    lv_obj_set_width(ui_StatusBarS2, 40);
    lv_obj_set_height(ui_StatusBarS2, 20);
    lv_obj_set_x(ui_StatusBarS2, 140);
    lv_obj_set_y(ui_StatusBarS2, -110);
    lv_obj_set_align(ui_StatusBarS2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_StatusBarS2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_StatusBarS2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBarS2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_StatusBarS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatusBarS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatusBarS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatusBarS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIndicatorS2 = lv_img_create(ui_StatusBarS2);
    lv_img_set_src(ui_WifiIndicatorS2, &ui_img_wifi_solid_png);
    lv_obj_set_width(ui_WifiIndicatorS2, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_WifiIndicatorS2, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_WifiIndicatorS2, 130);
    lv_obj_set_y(ui_WifiIndicatorS2, -110);
    lv_obj_set_align(ui_WifiIndicatorS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIndicatorS2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiIndicatorS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryIndicatorS2 = lv_img_create(ui_StatusBarS2);
    lv_img_set_src(ui_BatteryIndicatorS2, &ui_img_battery_full_solid_png);
    lv_obj_set_width(ui_BatteryIndicatorS2, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_BatteryIndicatorS2, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_BatteryIndicatorS2, 150);
    lv_obj_set_y(ui_BatteryIndicatorS2, -110);
    lv_obj_set_align(ui_BatteryIndicatorS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BatteryIndicatorS2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BatteryIndicatorS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
